#CentOS nodes/playbook

- name: Install prerequisites
  yum:
    name:
      - java-1.8.0-openjdk
      - epel-release
      - wget
      - which
    state: present
  become: yes

- name: Add Elasticsearch YUM repository
  become: yes
  yum_repository:
    name: elasticsearch-7.x
    description: Elasticsearch repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: 1
    state: present

- name: Add Elasticsearch YUM repository
  yum_repository:
    name: elasticsearch-7.x
    description: Elasticsearch repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: 1
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: 1
  become: yes

- name: Install Elasticsearch
  yum:
    name: elasticsearch
    state: present
  become: yes


- name: Enable and start Elasticsearch service
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
  become: yes

- name: Install Kibana
  yum:
    name: kibana
    state: present
  become: yes

- name: Enable and start Kibana service
  systemd:
    name: kibana
    enabled: yes
    state: started
  become: yes

- name: Install Logstash
  yum:
    name: logstash
    state: present
  become: yes

- name: Enable and start Logstash service
  systemd:
    name: logstash
    enabled: yes
    state: started
  become: yes

- name: Restart Elasticsearch and Kibana
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - elasticsearch
    - kibana

